name: Deploy WebApp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 20.x
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

   # - name: 'Run Azure webapp deploy action using publish profile credentials'
   #   uses: azure/webapps-deploy@v2
   #   with:
   #     app-name: emp36746139
    #    publish-profile: ${{ secrets.azureWebAppPublishProfile }}
